language: ruby
rvm:
 - 2.3.1

 addons:
   postgresql: "9.4"

services:
  - postgresql


before_script:
- bundle exec rake db:create RAILS_ENV=test
# - psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rake db:migrate

script: bundle exec rspec spec
